### ISSUE TITLE
Clean install config issues

### ISSUE THREAD

**Issue by dalager** [BuriedStPatrick/pwsh#3]
Installing on a clean windows 11 installation is not working.
- install works ok
But when restarting shell there is no files in the appdata folder where the script is looking.

**Comment by BuriedStPatrick** [comment]
Can reproduce! I think I fumbled some destination paths due to some colliding ideas about how the configs should be parsed.

Taking a look :)

**Comment by BuriedStPatrick** [comment]
For the time being, workaround is installing the default config file:

1. Run `patch.ps1` in repo
2. Select `(3) Install default config`
3. Reload your PowerShell session

**Comment by BuriedStPatrick** [comment]
@dalager Should be fixed in `3-clean-install-issues` :)

**Comment by BuriedStPatrick** [comment]
@dalager I'm going ahead with the PR merge. You can re-open if the problem persists.
